host: "localhost"
port: 8082

logConfig:
  level: "debug"
  filePath: "calendar.log"

dbConfig:
  host: "localhost"
  port: 5432
  dbName: "db_calendar"
  user: "db_calendar_user"
  password: "test"
  itemsPerQuery: 50
  repoType: "psql"

grpcAddress: "localhost:50051"
httpAddress: "localhost:50052"
